apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../policies/kyverno/block-pull-request-target.yaml
  - ../../policies/kyverno/require-referrers.yaml
  - ../../policies/kyverno/secretless.yaml
  - ../../policies/kyverno/verify-images.yaml
